---
output:
  html_document:
    toc: yes
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}


The R function `arima()` provides standard errors calculated using observed Fisher information. Suppose a parametric model has a single parameter, $\theta$, and the log-likelihood function when fitting this model to dataset is as follows:

```{r fisher_info, fig.width=5,fig.height=5, out.width="30%",echo=FALSE}
par(mai=c(1,1,0.1,0.1))
theta <- seq(from=0,to=10,length=200)
loglik <- -2000-(theta-5)^2
plot(theta,loglik,ty="l")
```

What is the observed Fisher information ($I_{\mathrm obs}$) for $\theta$?

It may be helpful to note that the observed Fisher information is accumulated over the whole dataset, not calculated per observation, so we don't have to know the number of observations, $N$.

Also, for time series models, we do not usually model observations as independent. Thus, the log-likelihood is not the sum of the log-likelihood for each observation. Its calculation involves consideration of the dependence, and is usually carried out by a computer program.

For checking your answer, it may help to know that the usual variance estimate for the maximum likelihood estimate, $\theta_{MLE}$, is $\var(\theta_{MLE}) \approx 1/I_{\mathrm obs}$.

A: $I_{\mathrm obs}=2$

B:  $I_{\mathrm obs}=1$

C: $I_{\mathrm obs}=1/2$

D: $I_{\mathrm obs}=1/4$

E: None of the above


